# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true # Quitar porque da error 

# Setup
title:               'Ecoinformática - AEET'
tagline:             ''
description:         'Grupo de Ecoinformática de la Asociación Española de Ecología Terrestre'
url:                 http://ecoinfAEET.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Ecoinformática_AEET
  github:            ecoinfAEET
  twitter:           ecoinf_aeet
  url:               https://twitter.com/ecoinf_aeet
  email:             ecoinf.aeet@gmail.com
  gravatar_md5:      4d17cceb49d4c54821502290f90d4041
  rss:               atom.xml

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/ecoinfAEET/ecoinfAEET.github.io

gems: 
  - jekyll-paginate
  - jekyll-feed