# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'Ecoinformática - AEET'
tagline:             ''
description:         'Grupo de Ecoinformática de la Asociación Española de Ecología Terrestre'
url:                 http://ecoinfAEET.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Ecoinformática_AEET
  github:            ecoinfAEET
  twitter:           ecoinf_aeet
  url:               https://twitter.com/mdo
  email:             ecoinf.aeet@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/ecoinfAEET/ecoinfAEET.github.io
