on:
  workflow_dispatch:
  schedule:
   - cron: "0 0 * * *"
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          install-r: true   
          
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: gsheet, fontawesome, leaflet, RJSONIO
          # dependencies: '"hard"'
      
      - name: Create profile for new members
        run: Rscript -e 'source("R/create_members_profile.R")'

      - name: Upload changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Upload members profiles
          
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
