on:
  workflow_dispatch:
  schedule:
   - cron: "0 0 * * *"
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          install-r: true   ## will use frozen R version (to save time) unless set to true

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
